accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from accounts_app import views


app_name = 'accounts_app'

urlpatterns = [
    # calls the builtin login form, template=html file which is required
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'),
        name='login'),
    # this automatically goes to the home page once the user signs out
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts_app:password_reset_done')),
        name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts_app:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

]

belmero_bluebin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from belmero_bluebin import views


urlpatterns = [
    path('', views.index, name='index'),
    path('logged_in/', views.logged_in, name='logged_in'),
    path('logged_out/', views.logged_out, name='logged_out'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('requisitions/', include('requisition_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

requisition_app/urls.py
from django.urls import path
from requisition_app import views
from django_filters.views import FilterView
from requisition_app.filters import RequisitionFilter
from django.contrib.auth.decorators import login_required

app_name = 'requisition_app'

urlpatterns = [
    path('requisition-request-create/<str:requester_id>/',
         views.requisition_request_create,
         name="requisition_request_create"),
    path('thank-you/',
         views.thank_you,
         name="thank_you"),
    path('requisition-search/',
         login_required(FilterView.as_view(
             filterset_class=RequisitionFilter,
             template_name='requisition_app/requisition_list.html')),
         name='requisition_search'),  # uses context filter.form and filter.qs
    path('requisition-request-inquiry/<int:pk>/',
         views.requisition_request_inquiry,
         name="requisition_request_inquiry"),
]

requisition_app/views.py
from django.shortcuts import render
from django.forms import inlineformset_factory
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from requisition_app import models
from requisition_app import forms


# Create your views here.
def requisition_request_create(request, requester_id):
    """
        Requisition Create
    """
    # retrieve installation values to identify hidden fields in template
    reqinstallation = models.ReqInstallation.objects.first()

    req_hdr = models.ReqHeader()  # empty parent model
    # create parent/hdr form
    req_hdr_form = forms.RequisitionHdrForm(
        instance=req_hdr, initial={'requester_id': requester_id})

    # instantiate inlineformset
    reqlineformset = inlineformset_factory(
        models.ReqHeader, models.ReqLine, form=forms.RequisitionLineForm,
        extra=reqinstallation.initial_number_of_lines)
    formset = reqlineformset(instance=req_hdr)

    if request.method == 'POST':
        # initial set
        req_hdr_form = forms.RequisitionHdrForm(request.POST, request.FILES)
        formset = reqlineformset(request.POST, request.FILES)

        if req_hdr_form.is_valid():
            parent = req_hdr_form.save(commit=False)  # save no commit
            parent.updated_date = timezone.now()  # was datetime.now()
            parent.requester_id = requester_id

            # set inlineformset using parent instance
            formset = reqlineformset(
                request.POST, request.FILES, instance=parent)

            if formset.is_valid():
                parent.save()
                formset.save()

                url = reverse('requisition_app:thank_you')
                return HttpResponseRedirect(url)

    return render(request, "requisition_app/requisition_request.html", {
        "form": req_hdr_form,
        "reqlineform": formset,
        "reqinstallation": reqinstallation,
        "requester_id": requester_id,
        "inquiry": False,
    })


def thank_you(request):
    """
        Thank you page
    """
    return render(request, 'requisition_app/thank_you.html')


@login_required
def requisition_request_inquiry(request, pk):
    """
        Requisition Inquiry
    """
    req_hdr = get_object_or_404(models.ReqHeader, pk=pk)

    # retrieve installation values to identify hidden fields in template
    reqinstallation = models.ReqInstallation.objects.first()

    req_hdr_form = forms.RequisitionHdrReadOnlyForm(
        instance=req_hdr)

    # instantiate inlineformset
    reqlineformset = inlineformset_factory(
        models.ReqHeader, models.ReqLine,
        form=forms.RequisitionLineReadOnlyForm)
    formset = reqlineformset(instance=req_hdr)

    # shares the same template as create but uses separate form to disable flds
    return render(request, "requisition_app/requisition_request.html", {
        "form": req_hdr_form,
        "reqlineform": formset,
        "reqinstallation": reqinstallation,
        "requester_id": req_hdr.requester_id,
        "inquiry": True,
    })


def get_req_hdr_columns():
    """
    Builds a tuple of all of the Req Hdr Fields
    Returns export_header
    """
    req_hdr_fields_qs = models.ReqIntegrationFileHdrFields.objects.all()
    req_hdr_fields_list = []
    for row in req_hdr_fields_qs:
        req_hdr_fields_list.insert(row.sequence, row.field_name)

    return req_hdr_fields_list


def get_req_line_columns():
    """
    Builds a tuple of all of the Req Line Fields except for id/pk
    Returns export_line
    """
    req_line_fields_qs = models.ReqIntegrationFileLineFields.objects.all()
    req_line_fields_list = []
    for row in req_line_fields_qs:
        req_line_fields_list.insert(row.sequence, row.field_name)

    return req_line_fields_list


def write_req_columns_to_file(writer, export_header, export_line):
    """
    Writes both the header and line columns to the file
    Returns writer
    """
    writer.writerow(export_header)
    writer.writerow(export_line)

    return writer


def get_and_write_req_data(export_data, req_line_fields_list, writer,
                           interfacetype, export_online_option, api_setup):
    """
    Using the header rows in export_data get the corresponding line rows
    (fields to export in req_line_fields_list) and then write both the header
    and line data to the file.  At the end update the record_hdr interface or
    export_online fields.
    interfacetype = "export" or "interface"
    export_online_option parm is only for "export" interfacetype (set to None)
    option values: = 1 (only new/changed rows) or 2 (all rows)
    Returns writer
    """
    for a in export_data:
        # header processing
        alist = list(a)

        # get hdr id from list for lookup and then remove it from list
        hdr_id = alist[0]
        alist.pop(0)

        # add header record identifier
        alist.insert(0, api_setup.header_row_type_id_in_file)
        a = tuple(alist)
        writer.writerow(a)

        # line processing
        lines = models.ReqLine.objects.filter(parent_id__pk=hdr_id). \
            values_list(*req_line_fields_list).order_by('id')
        for i in lines:
            ilist = list(i)
            # add line record identifier
            ilist.insert(0, api_setup.line_row_type_id_in_file)
            i = tuple(ilist)
            writer.writerow(i)
            # update record hdr that rows have been interfaced
            if interfacetype == 'interface':
                models.ReqHeader.objects.filter(pk=hdr_id).update(
                    interfaced=True,
                    last_interface_date=timezone.now()
                )
    return writer


def remove_leading_asterisk(field):
    '''
    removes leading * if it exists and returns value without *
    '''
    if str(field).find('*') != -1:
        field = str(str(field).split('*')[-1])
    return field

requisition_app/templates/requisition_app/requisition_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
  <h1>Requisitions Search Page</h1>

  <form method="GET">
      {% csrf_token %}
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
          {% bootstrap_form filter.form %}
          <!-- {{ filter.form.as_p }} -->

      <button class='btn btn-primary' type="submit" name="Submit">Submit</button>
      </div>
  </form>

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Search Results:</h3>
  </div>

  {% for req in filter.qs %}
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <p><a href="{% url 'requisition_app:requisition_request_inquiry' req.pk %}"> ID: {{ req.id }} - {{ req.requester_id }} - {{ req.business_unit }} - {{ req.location }} - {{ req.entered_date }} </p>
            <hr>
        </div>
      </div>
  {% endfor %}


{% endblock %}

requisition_app/templates/requisition_app/requisition_request.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% load requisition_app_templatetags %}

{% block content %}

<div class="row" id='headerrow'>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
        {% if reqinstallation.requisition_customer_logo %}
            <img src="{{reqinstallation.requisition_customer_logo.url}}" alt="missing logo">
        {% endif %}
        <!-- <img src="{% static 'images/logo.jpg' %}" alt="Belmero Inc missing image"> -->
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        {% if inquiry is False %}
            <h2><center> {{ reqinstallation.requisition_form_name }} </center></h2>
        {% else %}
            <h2><center> {{ reqinstallation.requisition_form_name }} Inquiry</center></h2>
        {% endif %}
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
         <p align="right"> Requester: {{ requester_id }} </p>
    </div>

</div>

{% if reqinstallation.requisition_top_of_page_instructions %}
    {% if inquiry is False %}
        <div class="alert alert-info" role="alert">
            {{ reqinstallation.requisition_top_of_page_instructions }}
        </div>
    {% endif %}
{% endif %}

<div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form_errors form error_types='all' %}

        <div class="row">
             <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
               <label for="{{ form.business_unit.label }}">{{ form.business_unit.label }}</label>
               {{ form.business_unit|addattribute:'class:form-control' }}
               {{ form.business_unit.errors.as_ul }}
             </div>
             <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
               <label for="{{ form.location.label }}">{{ form.location.label }}</label>
               {{ form.location|addattribute:'class:form-control'}}  <!-- custom templatetags I created -->
               {{ form.location.errors.as_ul }}
             </div>
        </div>

        {% if reqinstallation.req_hdr_custom_field_c10_hide_field is False or reqinstallation.req_hdr_custom_field_c30_hide_field is False or reqinstallation.req_hdr_custom_field_c60_hide_field is False %}
              <div class="row">
                  <!-- <h3>Additional Information</h3> -->
                  {% if reqinstallation.req_hdr_custom_field_c10_hide_field is False %}
                      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                           <label for="{{ form.custom_field_c10.label }}">{{ form.custom_field_c10.label }}</label>
                           {{ form.custom_field_c10|addattribute:'class:form-control'}}
                           {{ form.custom_field_c10.errors.as_ul }}
                      </div>
                  {% endif %}
                  {% if reqinstallation.req_hdr_custom_field_c30_hide_field is False %}
                      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                           <label for="{{ form.custom_field_c30.label }}">{{ form.custom_field_c30.label }}</label>
                           {{ form.custom_field_c30|addattribute:'class:form-control'}}
                           {{ form.custom_field_c30.errors.as_ul }}
                      </div>
                  {% endif %}
                  {% if reqinstallation.req_hdr_custom_field_c60_hide_field is False %}
                      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                           <label for="{{ form.custom_field_c60.label }}">{{ form.custom_field_c60.label }}</label>
                           {{ form.custom_field_c60|addattribute:'class:form-control'}}
                           {{ form.custom_field_c60.errors.as_ul }}
                      </div>
                  {% endif %}
              </div>
         {% endif %}

        <hr>

        {{ reqlineform.management_form }}

        {% for form in reqlineform %}  <!-- form is synonmous with line -->
        <!-- check all fields included hidden in the form for Errors -->
            <div class="line item" id="inputlines">
                 {% if form.instance.id %}
                      <span class="hidden line-id">{{ form.instance.id }}</span>
                 {% endif %}
                 {{ form.id.as_hidden }}  <!-- since we're not using form.as_p you have to have the key field on the form so it auto populates -->

                 {% bootstrap_formset_errors reqlineform %}
                 <!-- {% for err in form.non_field_errors %}
                    <p>Non-Field Error: {{ err }}</p>
                 {% endfor %} -->

                 {{ form.errors.as_ul }}

                 <div class="row">
                     <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <label for="{{ form.item_id.label }}">{{ form.item_id.label }}</label>
                        {{ form.item_id|addattribute:'class:form-control'}}
                        {{ form.item_id.errors.as_ul }}
                     </div>

                     {% if reqinstallation.bin_hide_field is False %}
                         <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <label for="{{ form.bin.label }}">{{ form.bin.label }}</label>
                            {{ form.bin|addattribute:'class:form-control'}}
                            {{ form.bin.errors.as_ul }}
                         </div>
                     {% endif %}

                     <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <label for="{{ form.qty.label }}">{{ form.qty.label }}</label>
                        {{ form.qty|addattribute:'class:form-control'}}
                        {{ form.qty.errors.as_ul }}
                     </div>
                 </div>

            </div>
        {% endfor %}

        <div class="clearfix"></div>

        {% if inquiry is False %}
            <div class="row" id='buttons'>
              <div class="clearfix"></div>
              <input class="btn btn-primary" type="submit" value="Save">
              <!-- <a href="{% url 'index' %}">back home</a> -->
            </div>
            <br>
        {% else %}
          <a href="{% url 'requisition_app:requisition_search'%}">Return to Search</a>
        {% endif %}

    </form>
</div>


{% endblock %}

requisition_app/templates/requisition_app/thank_you.html
{% extends "base.html" %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h2><strong>Thank You!</strong> You successfully submitted your Requisition</h2>
</div>


{% endblock %}