accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from accounts_app import views


app_name = 'accounts_app'

urlpatterns = [
    # calls the builtin login form, template=html file which is required
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'),
        name='login'),
    # this automatically goes to the home page once the user signs out
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts_app:password_reset_done')),
        name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts_app:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

]

belmero_bluebin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from belmero_bluebin import views


urlpatterns = [
    path('', views.index, name='index'),
    path('logged_in/', views.logged_in, name='logged_in'),
    path('logged_out/', views.logged_out, name='logged_out'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('requisitions/', include('requisition_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts_app/models.py
# from django.db import models
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        # username is a builtin var in auth.models.username,
        # this is the same User model you see in the Admin console
        return "@{}".format(self.username)

accounts_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm  #


class UserCreateForm(UserCreationForm):

    class Meta:  # metadata
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    # this creates field labels for the fields listed above
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"

accounts_app/views.py
# from django.shortcuts import render
# waits to transfer user until after they have hit the submit button
from django.urls import reverse_lazy
from django.views.generic import CreateView
from accounts_app import forms


# Create your views here.
# create view is used for creating new row/data using a form
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    # on a successful signup redirect to login page
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

accounts_app/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>

<br>
<div class="container">
    <p><a href="{% url 'accounts_app:password_reset' %}">Forgot Password?</a></p>
</div>

{% endblock %}

accounts_app/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="alert alert-success" role="alert">
  <h1>Your password has been changed!</h1>
</div>
<br>

<h4><a href="{% url 'accounts_app:login' %}">Click here to Log In</a></h4>


{% endblock %}

accounts_app/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

{% if validlink %}
    <form action="" method="post">
        {% csrf_token %}
        {% if form.errors %}
          {{ form.errors }}
        {% endif %}
        <!-- <div style="display:none">
            <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
        </div> -->
        <div class="alert alert-info" role="alert">
            <h4>Please enter (and confirm) your new password.</h4>

            <label for="new_password1">New Password:</label>
            <input type="password" class="form-control" name="new_password1" id="new_password1" placeholder="Enter your new password">

            <br>
            <label for="new_password2">Re-enter/Confirm Password:</label>
            <input type="password" class="form-control" name="new_password2" id="new_password2" placeholder="Enter your new password again to confirm it">

            <br>
            <input type="submit" class="btn btn-primary btn-lg" value="Change My Password">
        </div>
    </form>
</div>

{% else %}
    <h1>Password reset failed</h1>
    <h4>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</h4>

{% endif %}

{% endblock %}

accounts_app/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4>We've emailed you instructions for setting your password. </h4>
    <h4>If they haven't arrived in a few minutes, check your spam folder.
    </h4>
</div>

{% endblock %}

accounts_app/templates/accounts/password_reset_email.html
Your requested a password reset on Belmero's Supplier Returns Managed Service cloud software for email {{ email }}.

Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts_app:password_reset_confirm' uidb64=uid token=token %}

accounts_app/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}


<form action="" method="post">
    {% csrf_token %}
    {% if form.email.errors %}
      {{ form.email.errors }}
    {% endif %}

    <div class="alert alert-info" role="alert">
        <h4>Please enter your email below and click the Reset Password button</h4>
        <!-- <label for="email">Email address:</label> -->
        <br>
        <input type="email" class="form-control" name="email" id="email" placeholder="Enter the email associated with your account">
        <!-- {% bootstrap_form form %}
            <p>{{ form.email }}</p> -->
        <br>
        <input type="submit" class="btn btn-primary btn-lg" value="Reset password">
    </div>
</form>


{% endblock %}

accounts_app/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}

<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Sign Up">
    </form>
</div>

{% endblock %}