accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from accounts_app import views


app_name = 'accounts_app'

urlpatterns = [
    # calls the builtin login form, template=html file which is required
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'),
        name='login'),
    # this automatically goes to the home page once the user signs out
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts_app:password_reset_done')),
        name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts_app:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

]

belmero_bluebin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from belmero_bluebin import views


urlpatterns = [
    path('', views.index, name='index'),
    path('logged_in/', views.logged_in, name='logged_in'),
    path('logged_out/', views.logged_out, name='logged_out'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('requisitions/', include('requisition_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

requisition_app/urls.py
from django.urls import path
from requisition_app import views
from django_filters.views import FilterView
from requisition_app.filters import RequisitionFilter
from django.contrib.auth.decorators import login_required

app_name = 'requisition_app'

urlpatterns = [
    path('requisition-request-create/<str:requester_id>/',
         views.requisition_request_create,
         name="requisition_request_create"),
    path('thank-you/',
         views.thank_you,
         name="thank_you"),
    path('requisition-search/',
         login_required(FilterView.as_view(
             filterset_class=RequisitionFilter,
             template_name='requisition_app/requisition_list.html')),
         name='requisition_search'),  # uses context filter.form and filter.qs
    path('requisition-request-inquiry/<int:pk>/',
         views.requisition_request_inquiry,
         name="requisition_request_inquiry"),
]

templates/base.html
{% load requisition_app_templatetags %}
{% load staticfiles %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Belmero BlueBin SCM Solutions </title>


    {# Boot strap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {# JQuery - must be after Bootstrap or Bootstrap doesn't work correctly, eg dropdown menus don't work #}
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

    <!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script> -->
    <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->

    {# Google fonts #}
    <!-- google fonts fonts.google.com -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

    {# Our custom css #}
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

  </head>

  <body>
    <!-- Start - Navbar/Hamburger Code -->
    <nav class="navbar">  <!-- removed navbar-default navbar-inverse -->
      <!-- ="navbar navbar-default navbar-inverse navbar-fixed-top" -->

      <!-- Inside of a Container, container-fluid uses full page -->
      <div class="container-fluid">

        <!-- Brand and toggle get grouped for better mobile display -->
        <!-- This is the actual code that create the "hamburger icon" -->
        <!-- The data-target grabs ids to put into the icon -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

            <!--  Code for the hamburger icon-->
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Code for menu items -->
          <!-- <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/final_web_75x50.jpg' %}" alt="Belmero Inc"></a>  -->
          <!-- this is the Brand class, like for a logo or company name -->
          {% if user.is_authenticated %}  <!-- hyperlink back to index is only available to those that are logged in -->
              <a class="navbar-brand" href="{% url 'index' %}">Belmero BlueBin SCM Solutions</a>
          {% else %}
              <a class="navbar-brand">Belmero BlueBin SCM Solutions</a>
          {% endif %}
          <!-- <a class="navbar-brand" href="{% url 'index' %}">Supplier Returns Managed Service</a> -->
        </div>

        <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav navbar-right">

            {% if user.is_authenticated %}

              {% if request.user|has_group:"Belmero" %} <!-- for Belmero Internal Users -->
              <!-- dashboard views -->
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Requisitions</a>
                  <ul class='dropdown-menu'>
                    <li><a href="{% url 'requisition_app:requisition_request_create' request.user %}">Create Requisition for {{request.user}} </a> </li>
                    <li><a href="{% url 'requisition_app:requisition_search' %}">Requisition Search</a> </li>
                    <!-- <li role="separator" class="divider"></li> -->
                  </ul>
                </li>
              {% endif %}

              {% if request.user|has_group:"Admin" %}
                <li><a href="{% url 'admin:index' %}">Admin</a> </li>
              {% endif %}

              <!-- Everyone should be able to logout that's logged In, filtering/template tag logic is NOT needed -->
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"> <span class="glyphicon glyphicon-user" aria-hidden="true"></span> </a>
                <ul class='dropdown-menu'>
                  <!-- <li><a href="#">Hi {{ user.username }}</a></li> -->
                  <li><a href="{% url 'accounts_app:logout' %}">Log Out ({{ user.username }})</a> </li>
                </ul>
              </li>

            {% else %}
              <li><a href="{% url 'accounts_app:login' %}">Log In</a> </li>
              <!-- <li><a href="{% url 'accounts_app:signup' %}">Sign Up</a> </li> -->
            {% endif %}
          </ul>
        </div>
    </nav>

    <div class="container mycontent">

      {% block content %}

      {% endblock %}

    </div>


    <!-- placeholder for JavaScript -->
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>


    <!-- JQuery template tag placeholder, just like content above -->
    <script>
    $(document).ready(function(){
      {% block jquery %}
      {% endblock %}
    });
    </script>

  </body>

</html>

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<h1 class="center-text">Mobile Supply Chain</h1>

<!--
<div class="jumbotron">
  <h3><center> FOR BELMERO CUSTOMERS & PERSONNEL ONLY</center></h3>
</div>
<div>
  <p>This software is used to manage the Belmero Supplier Return Manage Service.
     Please use the menu bar at the top of the screen to navigate to the pages
     needed to complete the day-to-day work.
  </p>
</div>
-->

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <a href="{% url 'requisition_app:requisition_request_create' request.user %}"><img src="{% static 'files/purchase_requisition_image_150x100.png' %}" alt="Purchase Requisitions" id="tileimage"></a>
        <p id="tiletext">Create Requisitions</p>
        <br>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <a href=""><img src="{% static 'files/receiving2_image_150x100.jpg' %}" alt="Receiving" id="tileimage"></a>
        <p id="tiletext">FUTURE Receiving Functionality</p>
        <br>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <a href=""><img src="{% static 'files/delivery2_image_150x100.jpg' %}" alt="Delivery" id="tileimage"></a>
        <p id="tiletext">FUTURE Delivery Functionality</p>
        <br>
    </div>
</div>

{% endblock %}

templates/logged_in.html
{% extends "base.html" %}

{% block content %}

<div class="alert alert-success" role="alert">
  <h2>{{ user.first_name }} You have successfully logged in! </h2>
</div>

{% endblock %}

templates/logged_out.html
{% extends "base.html" %}

{% block content %}

<div class="alert alert-success" role="alert">
  <h2>{{ user.first_name }} You have successfully logged out! </h2>
</div>

{% endblock %}